[package]
name = "movableprompt"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive", "env", "string"] }
dirs = "5.0.1"
error-stack = "0.4.1"
rusqlite = { version = "0.29.0", features = ["bundled", "modern-full"] }
rusqlite_migration = "1.0.2"
serde = { version = "1.0.190", features = ["derive"] }
tera = "1.19.1"
thiserror = "1.0.50"
toml = "0.8.6"

[profile.release]
debug = 1
